function [R] = rot_verification_eq8(n, theta)

R = [n(1)^2+(1-n(1)^2)*cosd(theta) n(1)*n(2)*(1-cosd(theta))-n(3)*sind(theta) n(1)*n(3)*(1-cosd(theta))+n(2)*sind(theta);...
     n(1)*n(2)*(1-cosd(theta))+n(3)*sind(theta) n(2)^2+(1-n(2)^2)*cosd(theta) n(2)*n(3)*(1-cosd(theta))-n(1)*sind(theta);...
     n(1)*n(3)*(1-cosd(theta))-n(2)*sind(theta) n(2)*n(3)*(1-cosd(theta))+n(1)*sind(theta) n(3)^2+(1-n(3)^2)*cosd(theta)];